- name: Import the Openresty GPG key
  ansible.builtin.shell:
    shell:
      cmd: |
        wget -q -O - https://openresty.org/package/pubkey.gpg \
        | gpg --dearmor \
        | tee /usr/share/keyrings/openresty.gpg > /dev/null
    args:
      creates: /usr/share/keyrings/openresty.gpg