- name: Import the Openresty GPG key
  ansible.builtin.shell:
    cmd: |
      wget -O - https://openresty.org/package/pubkey.gpg \
      | sudo gpg --dearmor -o /usr/share/keyrings/openresty.gpg
    creates: /usr/share/keyrings/openresty.gpg