- name: Download OpenResty GPG key
  ansible.builtin.get_url:
    url: https://openresty.org/package/pubkey.gpg
    dest: /tmp/openresty.asc
    mode: '0644'

- name: Convert OpenResty GPG key to keyring
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/openresty.gpg /tmp/openresty.asc
    creates: /usr/share/keyrings/openresty.gpg